# Generated by Django 2.1.7 on 2019-04-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190401_1203'),
        ('blog', '0005_auto_20190401_1204'),
    ]

    operations = [
    ]
