# Generated by Django 2.1.7 on 2019-04-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190409_1144'),
        ('blog', '0006_auto_20190409_1139'),
    ]

    operations = [
    ]
