# Generated by Django 2.1.7 on 2019-04-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
    ]
