# Generated by Django 2.1.7 on 2019-04-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190408_1057'),
        ('shop', '0005_auto_20190421_1701'),
    ]

    operations = [
    ]
